version: "3.7"

services:
  spring-data:
    image: spring-data
    build: .
    restart: always
    ports:
      - 8888:8080
    links:
      - mongodb:database

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017


# version: "3.7"
# services:
#   application:
#     build: .
#     restart: always
#     ports:
#       - 8888:8888
#     links:
#       - mongodb:database
#   mongodb:
#     image: "mongo:latest"
#     restart: always
#     ports:
#       - 27017:27017
